#!/bin/python3
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 290)
        MainWindow.setMinimumSize(QtCore.QSize(460, 290))
        MainWindow.setMaximumSize(QtCore.QSize(460, 290))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("car.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.95)
        MainWindow.setStyleSheet("background-color: rgb(0, 111, 163);\n"
"border-top-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(14, 23, 99, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.doubleSpinBox_Tavolsag = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Tavolsag.setGeometry(QtCore.QRect(230, 23, 210, 44))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_Tavolsag.setFont(font)
        self.doubleSpinBox_Tavolsag.setDecimals(1)
        self.doubleSpinBox_Tavolsag.setMinimum(0.0)
        self.doubleSpinBox_Tavolsag.setMaximum(9999.0)
        self.doubleSpinBox_Tavolsag.setSingleStep(0.5)
        self.doubleSpinBox_Tavolsag.setProperty("value", 0.0)
        self.doubleSpinBox_Tavolsag.setObjectName("doubleSpinBox_Tavolsag")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(14, 88, 124, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox_Benzinar = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Benzinar.setGeometry(QtCore.QRect(230, 88, 210, 44))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_Benzinar.setFont(font)
        self.doubleSpinBox_Benzinar.setDecimals(1)
        self.doubleSpinBox_Benzinar.setMinimum(0.0)
        self.doubleSpinBox_Benzinar.setMaximum(999.0)
        self.doubleSpinBox_Benzinar.setProperty("value", 400.0)
        self.doubleSpinBox_Benzinar.setObjectName("doubleSpinBox_Benzinar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(14, 153, 126, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_Fogyasztas = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Fogyasztas.setGeometry(QtCore.QRect(230, 153, 210, 44))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_Fogyasztas.setFont(font)
        self.doubleSpinBox_Fogyasztas.setDecimals(1)
        self.doubleSpinBox_Fogyasztas.setMinimum(0.0)
        self.doubleSpinBox_Fogyasztas.setMaximum(999.0)
        self.doubleSpinBox_Fogyasztas.setSingleStep(0.1)
        self.doubleSpinBox_Fogyasztas.setProperty("value", 0.0)
        self.doubleSpinBox_Fogyasztas.setObjectName("doubleSpinBox_Fogyasztas")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(9, 220, 221, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(134, 199, 99);\n"
"color: rgb(0, 0, 0);\n"
"margin-right: 40\n"
"")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.lbl_eredmeny = QtWidgets.QLabel(self.centralwidget)
        self.lbl_eredmeny.setGeometry(QtCore.QRect(235, 218, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        self.lbl_eredmeny.setFont(font)
        self.lbl_eredmeny.setText("")
        self.lbl_eredmeny.setObjectName("lbl_eredmeny")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

############# button ###########################################################################
        self.pushButton.clicked.connect(self.koltseg)
################################################################################################
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mennyibe fog kerülni? "))
        self.label.setText(_translate("MainWindow", "Távolság:"))
        self.doubleSpinBox_Tavolsag.setSuffix(_translate("MainWindow", " (km)"))
        self.label_2.setText(_translate("MainWindow", "Benzin ára:"))
        self.doubleSpinBox_Benzinar.setSuffix(_translate("MainWindow", " (Ft)"))
        self.label_3.setText(_translate("MainWindow", "Fogyasztás:"))
        self.doubleSpinBox_Fogyasztas.setSuffix(_translate("MainWindow", " (l/100km)"))
        self.pushButton.setText(_translate("MainWindow", "K ö l t s é g"))

############# saját ###########################################################################
    def koltseg(self):
        self.tavolsag = float(self.doubleSpinBox_Tavolsag.value())
        self.benzinar = float(self.doubleSpinBox_Benzinar.value())
        self.fogyasztas = float(self.doubleSpinBox_Fogyasztas.value())

        self.eredmeny = (self.fogyasztas / 100) * self.tavolsag * self.benzinar
        self.eredmeny = round(self.eredmeny)
        self.eredmeny = str(self.eredmeny)
        self.eredmeny = self.lbl_eredmeny.setText(self.eredmeny + ' Ft')
################################################################################################

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())